In [1]:
!pip install transformers

In [2]:
!pip install torch

#### Importing required Libraries

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings
warnings.filterwarnings('ignore')

#### Load the dataset

In [4]:
df = pd.read_csv(r'C:\Users\ASUS\Desktop\BERT\Amazon_FoodReviews.csv')
df

Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
...        ...         ...             ...                              ...   
568449  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter   
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer   
568451  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"   
568452  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"   
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17   

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                          1                       1      5  1303862400   
1                          0                       0      1  1346976000   
2                          1                       1      4  1219017600   
3                          3                       3      2  1307923200   
4                          0                       0      5  1350777600   
...                      ...                     ...    ...         ...   
568449                     0                       0      5  1299628800   
568450                     0                       0      2  1331251200   
568451                     2                       2      5  1329782400   
568452                     1                       1      5  1331596800   
568453                     0                       0      5  1338422400   

                                   Summary  \
0                    Good Quality Dog Food   
1                        Not as Advertised   
2                    "Delight" says it all   
3                           Cough Medicine   
4                              Great taffy   
...                                    ...   
568449                 Will not do without   
568450                        disappointed   
568451            Perfect for our maltipoo   
568452  Favorite Training and reward treat   
568453                         Great Honey   

                                                     Text  
0       I have bought several of the Vitality canned d...  
1       Product arrived labeled as Jumbo Salted Peanut...  
2       This is a confection that has been around a fe...  
3       If you are looking for the secret ingredient i...  
4       Great taffy at a great price.  There was a wid...  
...                                                   ...  
568449  Great for sesame chicken..this is a good if no...  
568450  I'm disappointed with the flavor. The chocolat...  
568451  These stars are small, so you can give 10-15 o...  
568452  These are the BEST treats for training and rew...  
568453  I am very satisfied ,product is as advertised,...  

[568454 rows x 10 columns]

#### Using first 500 rows from the dataset 

In [5]:
batch_1 = df[:500]
print(batch_1['Text'].iloc[0])
batch_1

I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.


Id   ProductId          UserId                      ProfileName  \
0      1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1      2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2      3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3      4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4      5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
..   ...         ...             ...                              ...   
495  496  B000G6RYNE   APGAA43E3WPN7                           Darren   
496  497  B000G6RYNE    ABR7HU5H1KNE                            Keith   
497  498  B000G6RYNE   AJQD2WWJYOYFQ                          bubbles   
498  499  B000G6RYNE  A16YH487W9ZYO0                 Bruce G. Lindsay   
499  500  B000G6RYNE   A83YQC1XOU4CS                         J. Baker   

     HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                       1                       1      5  1303862400   
1                       0                       0      1  1346976000   
2                       1                       1      4  1219017600   
3                       3                       3      2  1307923200   
4                       0                       0      5  1350777600   
..                    ...                     ...    ...         ...   
495                     0                       0      5  1201392000   
496                     0                       0      5  1196726400   
497                     0                       0      4  1186617600   
498                     0                       0      4  1184198400   
499                     0                       0      5  1183420800   

                             Summary  \
0              Good Quality Dog Food   
1                  Not as Advertised   
2              "Delight" says it all   
3                     Cough Medicine   
4                        Great taffy   
..                               ...   
495                    amazing chips   
496                   Best Chip Ever   
497  Tangy, spicy, and sweet- oh my!   
498        An indulgence with a bite   
499                The best I've had   

                                                  Text  
0    I have bought several of the Vitality canned d...  
1    Product arrived labeled as Jumbo Salted Peanut...  
2    This is a confection that has been around a fe...  
3    If you are looking for the secret ingredient i...  
4    Great taffy at a great price.  There was a wid...  
..                                                 ...  
495  i rarely eat chips but i saw these and tried t...  
496  This is easily the best potato chip that I hav...  
497  Kettle Chips Spicy Thai potato chips have the ...  
498  Okay, I should not eat potato chips, nor shoul...  
499  I don't write very many reviews but I have to ...  

[500 rows x 10 columns]

#### Column list of the dataframe

In [6]:
batch_1.columns.tolist()

['Id',
 'ProductId',
 'UserId',
 'ProfileName',
 'HelpfulnessNumerator',
 'HelpfulnessDenominator',
 'Score',
 'Time',
 'Summary',
 'Text']

#### Dropping unnecessary columns

In [7]:
batch_1 = batch_1.drop(['Id','ProductId','UserId','ProfileName','HelpfulnessNumerator', 'HelpfulnessDenominator','Time',
 'Summary'], axis=1)
batch_1

Score                                               Text
0        5  I have bought several of the Vitality canned d...
1        1  Product arrived labeled as Jumbo Salted Peanut...
2        4  This is a confection that has been around a fe...
3        2  If you are looking for the secret ingredient i...
4        5  Great taffy at a great price.  There was a wid...
..     ...                                                ...
495      5  i rarely eat chips but i saw these and tried t...
496      5  This is easily the best potato chip that I hav...
497      4  Kettle Chips Spicy Thai potato chips have the ...
498      4  Okay, I should not eat potato chips, nor shoul...
499      5  I don't write very many reviews but I have to ...

[500 rows x 2 columns]

#### Check the value range for Rating Score 

In [8]:
batch_1['Score'].unique()

array([5, 1, 4, 2, 3], dtype=int64)

### Labeling the data according to scores

If the scores are greater than 3 then labeling as positive review, value =1, otherwise negative review, value=0

In [9]:
for i, row in batch_1.iterrows():
    if batch_1['Score'][i] >= 3:
        batch_1['Score'][i] = 1
    elif batch_1['Score'][i] < 3:
        batch_1['Score'][i] = 0        

In [10]:
batch_1

Score                                               Text
0        1  I have bought several of the Vitality canned d...
1        0  Product arrived labeled as Jumbo Salted Peanut...
2        1  This is a confection that has been around a fe...
3        0  If you are looking for the secret ingredient i...
4        1  Great taffy at a great price.  There was a wid...
..     ...                                                ...
495      1  i rarely eat chips but i saw these and tried t...
496      1  This is easily the best potato chip that I hav...
497      1  Kettle Chips Spicy Thai potato chips have the ...
498      1  Okay, I should not eat potato chips, nor shoul...
499      1  I don't write very many reviews but I have to ...

[500 rows x 2 columns]

#### Checking the labeled updated values

In [11]:
batch_1['Score'].values  

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [15]:
##Checking the text length in the text column

In [17]:
batch_1['Text_count'] = batch_1['Text'].str.len()
batch_1

Score                                               Text  Text_count
0        1  I have bought several of the Vitality canned d...         263
1        0  Product arrived labeled as Jumbo Salted Peanut...         190
2        1  This is a confection that has been around a fe...         509
3        0  If you are looking for the secret ingredient i...         219
4        1  Great taffy at a great price.  There was a wid...         140
..     ...                                                ...         ...
493      1  But if you happen to, like me, there is no bet...         103
495      1  i rarely eat chips but i saw these and tried t...         176
496      1  This is easily the best potato chip that I hav...         364
498      1  Okay, I should not eat potato chips, nor shoul...         209
499      1  I don't write very many reviews but I have to ...         375

[403 rows x 3 columns]

In [18]:
batch_1 = batch_1.drop(batch_1[batch_1['Text_count'] > 512].index) ##Dropping the rows with Text_Count > 512
batch_1

Score                                               Text  Text_count
0        1  I have bought several of the Vitality canned d...         263
1        0  Product arrived labeled as Jumbo Salted Peanut...         190
2        1  This is a confection that has been around a fe...         509
3        0  If you are looking for the secret ingredient i...         219
4        1  Great taffy at a great price.  There was a wid...         140
..     ...                                                ...         ...
493      1  But if you happen to, like me, there is no bet...         103
495      1  i rarely eat chips but i saw these and tried t...         176
496      1  This is easily the best potato chip that I hav...         364
498      1  Okay, I should not eat potato chips, nor shoul...         209
499      1  I don't write very many reviews but I have to ...         375

[403 rows x 3 columns]

In [21]:
batch_1[batch_1['Text_count'] > 512].index.any()  

False

In [22]:
### Checking the number of sentences are labeled as "positive" (= 1) and "negative" (= 0)

In [23]:
batch_1['Score'].value_counts()

1    360
0     43
Name: Score, dtype: int64

In [24]:
### Loading the Pre-trained BERT Model

#Here the variable, model, holds a pretrained distilBERT model

In [25]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.bias', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [26]:
# Model 1: Preparing the Dataset and Apply Deep Learning Model
## Preprocessing 

In [27]:
tokenized = batch_1['Text'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))  #tokenization
print(tokenized)

0      [101, 1045, 2031, 4149, 2195, 1997, 1996, 8995...
1      [101, 4031, 3369, 12599, 2004, 18414, 13344, 5...
2      [101, 2023, 2003, 1037, 9530, 25969, 3258, 200...
3      [101, 2065, 2017, 2024, 2559, 2005, 1996, 3595...
4      [101, 2307, 11937, 16329, 2012, 1037, 2307, 39...
                             ...                        
493    [101, 2021, 2065, 2017, 4148, 2000, 1010, 2066...
495    [101, 1045, 6524, 4521, 11772, 2021, 1045, 238...
496    [101, 2023, 2003, 4089, 1996, 2190, 14557, 909...
498    [101, 3100, 1010, 1045, 2323, 2025, 4521, 1455...
499    [101, 1045, 2123, 1005, 1056, 4339, 2200, 2116...
Name: Text, Length: 403, dtype: object


In [28]:
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])
print(padded)

[[ 101 1045 2031 ...    0    0    0]
 [ 101 4031 3369 ...    0    0    0]
 [ 101 2023 2003 ...    0    0    0]
 ...
 [ 101 2023 2003 ...    0    0    0]
 [ 101 3100 1010 ...    0    0    0]
 [ 101 1045 2123 ...    0    0    0]]


In [29]:
np.array(padded).shape

(403, 152)

In [30]:
batch_1.isnull().any()

Score         False
Text          False
Text_count    False
dtype: bool

In [31]:
batch_1.isna().any()

Score         False
Text          False
Text_count    False
dtype: bool

In [32]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

(403, 152)

In [33]:
#deep learning approach

In [34]:
input_ids = torch.tensor(padded)  
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_mask)

In [35]:
###Feature Engineering : selecting features and the label

In [36]:
features = last_hidden_states[0][:,0,:].numpy()
labels = batch_1['Score']

In [37]:
#Train Test Split

In [38]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)

In [39]:
#logistic regression model

In [41]:
lr_clf = LogisticRegression()
lr_clf.fit(train_features, train_labels)
lr_clf.score(test_features, test_labels)

0.900990099009901

In [42]:
#dummy classifier

In [43]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier()

scores = cross_val_score(clf, train_features, train_labels)
print("Dummy classifier score: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Dummy classifier score: 0.891 (+/- 0.02)


# Classification : with pipeline API

In [44]:
from transformers import pipeline


In [45]:
# Allocate a pipeline for sentiment-analysis
Sentiment_classifier = pipeline('sentiment-analysis')

In [46]:
Sentiment_classifier('We are very happy to introduce pipeline to the transformrs repository.')

[{'label': 'POSITIVE', 'score': 0.9997642636299133}]

In [47]:
Sentiment_classifier('The food tastes good')

[{'label': 'POSITIVE', 'score': 0.9998620748519897}]

In [48]:
Sentiment_classifier(batch_1['Text'].iloc[300])

[{'label': 'POSITIVE', 'score': 0.9328588247299194}]

In [49]:
batch_1['Text'].iloc[300]

"I was looking for a replacement for Timothy's Kona Blend which is no longer carried on Amazon.  This coffee from Green Mountain is very nice, but not strong enough for me.  If you like milder coffees, then this one is for you."

In [50]:
batch_1['Text'].iloc[400]

"This is easily the best potato chip that I have ever had.  Look at the ingredients:  Ginger and 3 types of hot pepper.  How can you go wrong?<br /><br />Obviously, not for you if you don't like spicy food. But, if you DO like spicy food, you'll probably love these.  They have that hot-with-a-hint-of-sweetness flavor combo that is prevalent in a lot of Thai food."

In [51]:
Sentiment_classifier(batch_1['Text'].iloc[400])

[{'label': 'POSITIVE', 'score': 0.9997544288635254}]

In [52]:
Sentiment_classifier(batch_1['Text'].iloc[256])

[{'label': 'POSITIVE', 'score': 0.9678064584732056}]

In [53]:
batch_1['Text'].iloc[256]

'I was amazed at how quickly it arrived!  It is a cute stocking stuffer, but only OK as far as user appeal.  You get what you pay for.'

In [60]:
import pickle

In [61]:
pickle.dump(lr_clf, open('model.pkl', 'wb'))

In [62]:
model = pickle.load(open('model.pkl', 'rb'))